### PR TITLE
Add support for CL generic methods

### PR DESCRIPTION
**Pull request by DamienCassou**
```emacs
(progn
  (require 'xref)
  (helpful-function #'xref-location-marker))
```

Will give you the list of implementation for this generic method.

### CODE REVIEW

**Comment by DamienCassou** [comment]
The build failure doesn't seem to be related to my PR.

**Comment by DamienCassou** [comment]
On a properly documented set of methods, this looks like this:

**Comment by DamienCassou** [comment]
ping

**Comment by DamienCassou** [comment]
up

**Comment by Wilfred** [comment]
Neat! Thanks :)

**Pull request merged**
