### PR TITLE
Do not depend on shut-up package

### PR DESCRIPTION
**Pull request by tarsius**
It seems unnecessary to pull in this dependency.

### CODE REVIEW

**Comment by Wilfred** [comment]
I'm happy to remove shut-up, but this PR isn't correct. I think the lambda has some mismatched parens. This doesn't work:

```
(cl-letf ((symbol-function #'message)
	  (lambda (_format-string) &rest _args))
  (message "hello"))
```

This is why the tests are failing.

I also think we'll need to add shut-up as a dev dependency in the `Cask` file, or do the same refactoring to the test suite too.

**Comment by tarsius** [comment]
Sorry about that. Build succeeds now.

**Comment by tarsius** [comment]
Force pushed a second time in order to replace tabs with spaces.

I recommend you enforce the use of spaces, instead of relying on everyone using the same global value for `tab-indent` as you. I prefer spaces too, but I have left the global alone because changing it on my machine doesn't change it on the machines of everyone contributing to my projects. :-)

**Comment by tarsius** [comment]
Friendly ping.

**Comment by Wilfred** [comment]
Merged in 897feba, thanks.

**Pull request closed without merging**
